version: '3'

services:
  web-app:
    container_name: flascompose_web-app
    image: idubi/flask-app:lts
    ports:
      - "5000:5000"
    environment:
      DB_USER: idubi
      DB_PASSWORD: idubi
      DB_NAME: idubi
      DB_TYPE: postgresql
      DB_HOST: postgres-db
      DB_PORT: 5432
    depends_on:
      - postgres-db
    networks:
      - flask-ntwrk
  postgres-db:
    container_name: flascompose_postgres-db
    image: postgres
    environment:
      POSTGRES_USER: idubi
      POSTGRES_PASSWORD: idubi
      POSTGRES_DB: idubi
    ports:
      - "5432:5432"
    networks:
      - flask-ntwrk   
networks:
  flask-ntwrk:
    driver: bridge




# healthcheck:
#       test: ["CMD-SHELL", "PGPASSWORD=idubi psql -U idubi -d idubi -c 'SELECT 1 FROM user LIMIT 1;' > /dev/null || exit 1"]
#       interval: 30s
#       timeout: 15s
#       retries: 5

# networks:
#   - app-network
# networks:
#   app-network:

    # networks:
    #   - app-network
