apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: flaskapp-python
spec:
  selector: 
    matchLabels:
      app: postgres-db
  replicas: 1  # Single replica for the database
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: postgres
        env:
        - name: POSTGRES_USER
          value: "idubi"
        - name: POSTGRES_PASSWORD
          value: "idubi"
        - name: POSTGRES_DB
          value: "idubi"
        ports:
        - containerPort: 5432
