apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: flaskapp-python
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP 
      port: 5432
      targetPort: 5432
---      
apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: flaskapp-python
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer